version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xlr8travel
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/xlr8travel?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"

  frontend:
    build:
      context: ./frontend
      args:
        # build‑time variable used by next.config.mjs
        NEXT_PUBLIC_BACKEND_URL: "http://backend:8080"
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
    environment:
      # run‑time variables for both client and middleware.ts
      NEXT_PUBLIC_BACKEND_URL: "${NEXT_PUBLIC_BACKEND_URL}"
      BACKEND_URL: "http://backend:8080"
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}"
    depends_on:
      - backend
    ports:
      - "3000:3000"

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8082:8080'

  prometheus:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    image: prometheus-custom:latest
    ports:
      - '9090:9090'
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=root   # change me
    ports:
      - '3001:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  db-data:
  grafana-data:
