version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xlr8travel
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/xlr8travel?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

  frontend:
    build:
      context: ./frontend
      args:
        # build‑time variable used by next.config.mjs
        NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    environment:
      # run‑time variables for both client and middleware.ts
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data:
