package org.example.xlr8travel.dto;

// Add necessary validation annotations if desired (e.g., @NotBlank)
// import jakarta.validation.constraints.*;

public class CheckoutRequestDTO {

    private String customerName;
    private String customerEmail;
    // Add any other billing fields (address, etc.) needed by your OrderService

    // *** IMPORTANT ***
    // DO NOT include raw card number, expiry, CVV here.
    // Include a field for the payment token generated by your frontend payment integration.
    // private String paymentMethodToken; // Example field name

    // Getters and Setters
    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    // Getter/Setter for paymentMethodToken...
    // public String getPaymentMethodToken() { return paymentMethodToken; }
    // public void setPaymentMethodToken(String paymentMethodToken) { this.paymentMethodToken = paymentMethodToken; }
}